### ISSUE TITLE
RG NANO screen does not displayed

### ISSUE THREAD

**Issue by ar623zium** [DrUm78/FunKey-OS#10]
thanx

**Comment by DrUm78** [comment]
Because you used the `FunKey-sdcard-DrUm78.img` file that is only for the FunKey S device. Please use `FunKey-sdcard-DrUm78_RG_Nano.img` with the RG Nano as explained on my page.

**Comment by manolowastaken** [comment]
I have the same problem, did the same process using FunKey-sdcard-DrUm78_RG_Nano.img on the same sd card and on a new one and no changes

**Comment by DrUm78** [comment]
@manolowastaken I tested it myself again and that works flawlessly. Not sure but I know that some softwares may not flash correctly the image for the FunKey S, so make sure to use [Win32 Disk Imager](https://win32-disk-imager.en.uptodown.com).
