### ISSUE TITLE
QOL suggestion for PicoArch & Default emulators in RetroFE

### ISSUE THREAD

**Issue by DynaMight1124** [DrUm78/FunKey-OS#11]
The common theme seems to be that the PicoArch cores are recommended over the stock Funkey emulators (even the ones which are actively updated). Would it be possible to set these as the default when loading games from RetroFE? even if there was a toggle in Gmenu2x to swap between them if some wanted the originals.

Also when loading non-RetroFE cores via the Libretro menu, would it be possible to set these to specific directories, so the Pico8 core will look into a directory called Pico8, rather than needing to navigate to the directory from root. Its not a huge problem, but does allow for a nicer user experience.

Every single core doesnt need a directory assigned but the most common ones would be handy.

**Comment by DrUm78** [comment]
Yeah I already thought about that but not sure tbh as most of your savestates won't be compatible anymore or will have to be moved to PicoArch folder.

For the PicoArch suggestion, I already proposed to neonloop a way to remember the folder for each core when you pick a ROM, he said it was a good idea so he may do it one day, so not on my side but I will implement it for sure in my custom OS if he does it.

**Comment by DrUm78** [comment]
@DynaMight1124 neonloop just committed the "last played" feature, so now it remembers the last ROM you launched for each core. I implemented this change in my custom OS, you can grab the update here: https://github.com/DrUm78/FunKey-OS/releases

**Comment by DynaMight1124** [comment]
Thats awesome, good work to you and neonloop.

**Comment by DrUm78** [comment]
I finally replaced all the default emulators by Libretro cores, see my release page.
