### ISSUE TITLE
Funkey s sound bug

### ISSUE THREAD

**Issue by MUPM** [DrUm78/FunKey-OS#13]
**Describe the bug**
Lastest funkey s custom OS is can't output sound, it's almost all emulator
And can't run libretro core, GBA emulator

Where can i find older version of custom os?
Anyway thanks to your custom work :) 60fps is huge implove!

**Comment by DrUm78** [comment]
Sound is working fine for me, not sure what you mean. Do you have any example or a video?

For Libretro, you need to put the cores in `Libretro/cores/` to run your games, they are not included by default. You can find a pack on Discord here: https://discord.com/channels/728036844142592000/827408202886414346/1070740429189951549

**Comment by MUPM** [comment]
I test os on powkiddy q36, there have specs different? but previous version is worked perfectly.
Libretro core too, test fb2012 core and prboom. neither of them can't run on this version of the os.
I deleted the previous version, so I test this problem with original os, sound works on that os.

hmm.. but your device is work correctly, I don't know what is problem

**Comment by DrUm78** [comment]
I made a mistake in the FunKey S/Q36 version (the RG Nano was fine though), please download the OS again and tell me if that's fine on your side. 🙏

**Comment by MUPM** [comment]
It's great! now all function nicely work.
Thanks😊
