### ISSUE TITLE
Suggestion of RetroFE WonderSwan mednafen-09x.cfg file for Y1~Y4 button

### ISSUE THREAD

**Issue by MUPM** [DrUm78/FunKey-OS#15]
I Edited in usr/games/mednafen-09x.cfg for use wonder swan Y1~4 button.
It useful some game (ex. wild card, judgement silver gun and some portrait game)

Landscape game key add
L - Y4
R - Y2
Y - Y3
X - Y1

Keyfile only use for portrait game.
Keyfile change button contain A and B, in case resume game, Use L R button

**Comment by DrUm78** [comment]
Not sure what to do with this as I don't know WonderSwan at all. I can only replace the default `mednafen-09x.cfg` file with this one in `/usr/games`, so that means every game will use the new one, is it what you proposed?
Also I cannot integrate .key file as I cannot predict what games use portrait, users have to do it themselves while naming it the same way as the ROM.

**Comment by MUPM** [comment]
Yes, because Y1-Y4 button is not mapped in the existing cfg file, simply modified Y1-Y4 to unassigned buttons.
cfg file only changed this part for 4button assign.


;wswan, Built-In, Gamepad: Y3(Y DOWN ↓)
wswan.input.builtin.gamepad.down-y keyboard 121

;wswan, Built-In, Gamepad: Y4(Y LEFT ←)
wswan.input.builtin.gamepad.left-y keyboard 109

;wswan, Built-In, Gamepad: Y2(Y RIGHT →)
wswan.input.builtin.gamepad.right-y keyboard 110

;wswan, Built-In, Gamepad: Y1(Y UP ↑)
wswan.input.builtin.gamepad.up-y keyboard 120


Key file is just attached for those who need vertical screen play,
I think so too, only need to replace the cfg file for use every wonderswan button.

I checked the cfg file again and found the part where I personally changed neogeo pocket language to Japanese, so I reattached file with only the Y button modified.
[mednafen-09x.zip](https://github.com/DrUm78/FunKey-OS/files/12470623/mednafen-09x.zip)

**Comment by DrUm78** [comment]
You also those changes, not sure why and what that means:
```
 ;Birth Day
-wswan.bday 23
+wswan.bday 6

 ;Blood Type
-wswan.blood O
+wswan.blood B

 ;Birth Month
-wswan.bmonth 6
+wswan.bmonth 10

 ;Sex
-wswan.sex F
+wswan.sex M
```

**Comment by MUPM** [comment]
Sorry I missed it, I think changed it when playing a WS game that requires a birthday XD
Not need birthday part.
I think it would be nice to just change the y button part.

**Comment by DrUm78** [comment]
I won't release any new version of my OS, I stopped the development. Ticket closed.

**Comment by DrUm78** [comment]
I finally replaced all the default emulators by Libretro cores, you can now map all the button in PicoArch settings, see my release page.
