### ISSUE TITLE
Harmonize RetroFE emulators using PicoArch

### ISSUE THREAD

**Issue by willbelr** [DrUm78/FunKey-OS#16]
First of all, Thank you for your great work!

If I may make a suggestion; as proposed recently (https://github.com/DrUm78/FunKey-OS/issues/11), even though it would be a breaking update,  I believe that using PicoArch by default for all platforms is a required change, and the sooner the better. 

That change would bring several benefits;

- Uniformity: configuration, bios files, states, etc, are all grouped in one single place
- Versatility: by using PicoArch, more customization is possible as the `advanced options` menu gets unlocked for all cores. This enables easy access to many useful settings, such as assigning core-specific aspect ratio
- Extensibility: makes it more straightforward to add new core or replace existing ones. This enables an easier implementation of new cores, tradeoffs for compability/accuracy, etc.
- Quality: Allows for better cores and extend compability for more games (ie. Road Rush for PS1, etc.) 

These days, it appears to be the "standard" approach (ie. OnionOs, MinUI, etc).
The task is a perfect fit for PicoArch purpose, so why not use it ?

**Comment by DrUm78** [comment]
It's already been discussed and PicoArch is alreadyavailable as an alternate solution in my custom OS, people just need to copy the cores in Libretro/cores/, that's quite easy to use for those who read the documentation.
Also, integrating core building automation in my OS and replacing all the stock emulators would need a bit of work, and I have other priorities right now so I don't think I will do it, sorry.

**Comment by DrUm78** [comment]
I finally replaced all the default emulators by Libretro cores, see my release page.

**Comment by willbelr** [comment]
Great new, thank you
