### ISSUE TITLE
Can we update the DOSBox Pure repository?

### ISSUE THREAD

**Issue by bulzipke** [DrUm78/FunKey-OS#2]
**Is your feature request related to a problem? Please describe.**
I don't know if I can write this question here. But I have a question because it says on wiki that you built a DOSBox Pure.
DOSBox Pure recently updated its key mapping function, which is awesome. It would be cool if it was applied to Funkey S.

**Describe the solution you'd like**
However, the wiki does not have a repository, so I cannot update it myself.
If you don't mind, could you build a latest opk?

**Additional context**
I think your work on Funkey S is very cool.
I salute you for all your efforts :)

**Comment by DrUm78** [comment]
Sure, here is the OPK with the latest source code compiled. I just tested Alley Cat and it still seems that there is still no possibility to change the controls.
Please note that I compiled it with GCC 10.2 (the FunKey S version) and that this is not recommended by the author (9 should be used instead) as it may make a buggy binary. Anyway, please tell me if controls are now better. If so, then I will add this core to my essential pack: https://github.com/DrUm78/sdlretro/releases.
Thanks.

[DOSBox_Pure_funkey-s.zip](https://github.com/DrUm78/FunKey-OS/files/8589038/DOSBox_Pure_funkey-s.zip)

**Comment by bulzipke** [comment]
It runs perfectly !

I did the key mapping as below.
```
A Button = K
B Button = H / Up arrow
X Button = T
Y Button = A
SELECT = ESC key
ENTER = N / Enter key
```

I don't know if it's okay to upload this, but I'll delete it if it's a problem.
[Alley.Cat.zip](https://github.com/DrUm78/FunKey-OS/files/8596378/Alley.Cat.zip)
EDIT: I edited your post to keep only the "PADMAP.DBP" file.

Thank you again for your hard work!

**Comment by DrUm78** [comment]
Oh so the update is better than before? What are the improvements? Not sure what you uploaded, what is it?
If you think this update is worth it, I will add it to my essential core pack.

**Comment by bulzipke** [comment]
Gamepad mapper have been added to this update(https://github.com/schellingb/dosbox-pure/commit/69d33559ca4b4fbe1ba6cee1933b129607088544)

If exists PADMAP.DBP file in a zip, DOSBox Pure use this file for key mapping.
And there is a PADMAP.DBP with Allycat in the file I uploaded. 
User can just load it from the DOSBox Pure core. Don't have to add any additional settings for play.

It worked perfectly on a Funkey s :)

**Comment by DrUm78** [comment]
Good news then. :)

**Comment by DrUm78** [comment]
@bulzipke BTW, what is the easiest way to generate those .DBP files? It's not plain text, so not sure how you generated it (and I don't find anything into the doc). With desktop Libreto/RetroArch? I think some users would be very interested on the FunKey S discord if an easy way to do it existed.

**Comment by bulzipke** [comment]
I created DBP file in Desktop RetroArch.
I think this is the best way :)

**Comment by DrUm78** [comment]
I just installed the latest desktop Libretro/RetroArch and all I get is some .rmp files with plain text. 🤔 
Can you tell me the exact version/platform you run and the steps to get this .DBP file? Thanks! :)

**Comment by bulzipke** [comment]
I didn't use the rmp file. I created the dbp file as below.

```
1. RetroArch Windows Download (64bit) 7z file
 : current version = 1.10.3
2. Settings -> Input -> Port 1 Controls -> L3 Button (Thumb)
 : in my case = F12
3. Main Menu -> Load Core -> Download a Core -> DOS (DOSBox-Pure)
 : current version = 0.9.1
4. Load game zip file
 : in this case = my_rom_path/aaa_blah_blah.zip
5. F12(my L3 key button) -> PAD MAPPER -> custom key mapping -> Close Mapper
6. dbp file in saves folder
 : in this case dbp file in saves/aaa_blah_blah.zip
7. Combine dbp file(6) into game file(4)
```

If you need anything from me, feel free to tell me!

**Comment by DrUm78** [comment]
Nice, it works, thanks. :)
BTW, you can open the pad mapper directly on the FunKey by pressing left d-pad then Fn key (release Fn key before left d-pad or the virtual keyboard will close). PADMAP.DBP will be saved in FunKey/.sdlretro/saves/dosbox-pure.

![IMG_0158](https://user-images.githubusercontent.com/46139740/166151812-980aae86-5ca7-4fa2-8871-bbb477666568.PNG) ![IMG_0161](https://user-images.githubusercontent.com/46139740/166151808-8ff0e003-038f-4d74-b253-8cbe0c967b38.PNG)

**Comment by DrUm78** [comment]
Made an "official" release here: https://github.com/DrUm78/dosbox-pure/releases
Thanks again for your help. 👍
