### ISSUE TITLE
[not really an issue] Gratitude - Hope project is going fine!

### ISSUE THREAD

**Issue by gabuzom** [DrUm78/FunKey-OS#20]
Hello there,

Pardon me using an issue to send such a generic message:

I want to thank you for your fork of FunKey-OS for the RG-Nano! It makes it shine and roar and work remarkably better than with stock! I really appreciate the improvements you've brought through all that work!

I am curious, as the project didn't move for a while, if you consider it "done" or still plan to work on it. But was mostly wanting to send encouragements! If you ever hesitated wondering if this project was useful, was being appreciated or so, well get sure it is! <3

(feel free to erase this message when you've read it)

**Comment by DrUm78** [comment]
Thank you for your message. I'm not sure I will release any new major version of my OS though, I reached most of my objectives regarding it, unless I get some new ideas of course. Regards.

**Comment by DrUm78** [comment]
I finally published a new release in which I replaced all the default emulators by Libretro cores, see my release page.
