### ISSUE TITLE
Show battery % all the time / Reduce frame buffer font size

### ISSUE THREAD

**Issue by pcmdx** [DrUm78/FunKey-OS#24]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to see the battery level all the time but the status line text takes up too much screen area.

**Describe the solution you'd like**

Ideally I'd like a small battery % value in the corner, but I understand that might be a lot of work.

**Describe alternatives you've considered**

A workaround could be making the frame buffer font size smaller so it takes up less screen area. `MINI4x6` has come up in my search here:

https://www.kernel.org/doc/html/v6.8/fb/fbcon.html

**Additional context**

I did try altering the font myself by editing `u-boot.env` and pointing `fw_env.config` to it, but it didn't seem to have any impact.

I'm happy to undertake this work myself if I'm pointed in the right direction.

**Comment by DrUm78** [comment]
Not something I planned, all the notifications have been set with this font size in mind, I think it's just fine how it is currently.

**Comment by pcmdx** [comment]
No worries @DrUm78, I understand. I'm happy to do it for my personal build, if you know how to change it?
