### ISSUE TITLE
build picodrive error 2

### ISSUE THREAD

**Issue by SunnyIMG** [DrUm78/FunKey-OS#3]
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘LzmaEncProps_Init’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:64:4: error: ‘CLzmaEncProps’ {aka ‘struct _CLzmaEncProps’} has no member named ‘affinity’
   64 |   p->affinity = 0;
      |    ^~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: At top level:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:389:3: error: unknown type name ‘IMatchFinder2’
  389 |   IMatchFinder2 matchFinder;
      |   ^~~~~~~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘ReadMatchDistances’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1098:31: error: request for member ‘GetNumAvailableBytes’ in something not a structure or union
 1098 |   p->numAvail = p->matchFinder.GetNumAvailableBytes(p->matchFinderObj);
      |                               ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1100:37: error: request for member ‘GetMatches’ in something not a structure or union
 1100 |     const UInt32 *d = p->matchFinder.GetMatches(p->matchFinderObj, p->matches);
      |                                     ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1127:40: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 1127 |         const Byte *p1 = p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - 1;
      |                                        ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘GetOptimum’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1266:26: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 1266 |     data = p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - 1;
      |                          ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1294:7: note: in expansion of macro ‘MOVE_POS’
 1294 |       MOVE_POS(p, len - 1)
      |       ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1305:7: note: in expansion of macro ‘MOVE_POS’
 1305 |       MOVE_POS(p, mainLen - 1)
      |       ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1489:11: note: in expansion of macro ‘MOVE_POS’
 1489 |           MOVE_POS(p, delta);
      |           ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1592:26: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 1592 |     data = p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - 1;
      |                          ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘GetOptimumFast’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2005:24: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 2005 |   data = p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - 1;
      |                        ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2019:7: note: in expansion of macro ‘MOVE_POS’
 2019 |       MOVE_POS(p, len - 1)
      |       ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2032:5: note: in expansion of macro ‘MOVE_POS’
 2032 |     MOVE_POS(p, mainLen - 1)
      |     ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2063:5: note: in expansion of macro ‘MOVE_POS’
 2063 |     MOVE_POS(p, repLen - 1)
      |     ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2085:24: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 2085 |   data = p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - 1;
      |                        ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:1090:19: error: request for member ‘Skip’ in something not a structure or union
 1090 |     p->matchFinder.Skip(p->matchFinderObj, (UInt32)(num)); }
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2106:5: note: in expansion of macro ‘MOVE_POS’
 2106 |     MOVE_POS(p, mainLen - 2)
      |     ^~~~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘LzmaEnc_CodeOneBlock’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2407:19: error: request for member ‘Init’ in something not a structure or union
 2407 |     p->matchFinder.Init(p->matchFinderObj);
      |                   ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2422:23: error: request for member ‘GetNumAvailableBytes’ in something not a structure or union
 2422 |     if (p->matchFinder.GetNumAvailableBytes(p->matchFinderObj) == 0)
      |                       ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2427:31: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 2427 |     curByte = *(p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - p->additionalOffset);
      |                               ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2433:21: error: request for member ‘GetNumAvailableBytes’ in something not a structure or union
 2433 |   if (p->matchFinder.GetNumAvailableBytes(p->matchFinderObj) != 0)
      |                     ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2478:28: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 2478 |       data = p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - p->additionalOffset;
      |                            ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2673:25: error: request for member ‘GetNumAvailableBytes’ in something not a structure or union
 2673 |       if (p->matchFinder.GetNumAvailableBytes(p->matchFinderObj) == 0)
      |                         ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘LzmaEnc_Alloc’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2770:36: warning: passing argument 2 of ‘MatchFinder_CreateVTable’ from incompatible pointer type [-Wincompatible-pointer-types]
 2770 |     MatchFinder_CreateVTable(&MFB, &p->matchFinder);
      |                                    ^~~~~~~~~~~~~~~
      |                                    |
      |                                    int *
In file included from pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:18:
pico/cd/libchdr/deps/lzma-19.00/include/LzFind.h:106:62: note: expected ‘IMatchFinder *’ {aka ‘struct _IMatchFinder *’} but argument is of type ‘int *’
  106 | void MatchFinder_CreateVTable(CMatchFinder *p, IMatchFinder *vTable);
      |                                                ~~~~~~~~~~~~~~^~~~~~
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c: In function ‘LzmaEnc_GetCurBuf’:
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2969:24: error: request for member ‘GetPointerToCurrentPos’ in something not a structure or union
 2969 |   return p->matchFinder.GetPointerToCurrentPos(p->matchFinderObj) - p->additionalOffset;
      |                        ^
pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.c:2970:1: warning: control reaches end of non-void function [-Wreturn-type]
 2970 | }
      | ^
make[2]: *** [Makefile:387: pico/cd/libchdr/deps/lzma-22.01/src/LzmaEnc.o] Error 1
make[1]: *** [package/pkg-generic.mk:250: /home/Drum78-FunKey-OS/FunKey/output/build/picodrive-v1.4-funkey-s/.stamp_built] Error 2
make: *** [Makefile:23: _all] Error 2

**Comment by DrUm78** [comment]
Try to remove the archive in 'download/picodrive/' and in 'FunKey/output/build/' and compile again.

**Comment by SunnyIMG** [comment]
this wrong is still alive

**Comment by DrUm78** [comment]
I do not have this error, the problem must be with your setup.
