### ISSUE TITLE
Can Funkey S be used for AttractMode player?

### ISSUE THREAD

**Issue by bulzipke** [DrUm78/FunKey-OS#7]
**Is your feature request related to a problem? Please describe.**
For me, the FunKey S is more of a desktop accessory than a plaything, so I keep it switched on in my office, but the screen is boring. So I remembered EmulationStation's screensaver feature, which plays the boxart or attracemode video of a playlist at a certain time.

**Describe the solution you'd like**
I think I saw that RetroFe has attractmode as a build option, but I don't know if that's actually a working feature.

**Describe alternatives you've considered**
With the limited hardware specifications of the FunKey S, video previewing may not be an option. Even if it's just a random preview of box art, I think it would be a fun addition.

**Additional context**
In fact, I don't know if this is the right place to put it. I'm always grateful for your work, and I want to help where I can.

**Comment by DrUm78** [comment]
I tried to enable the attract mode and it seems it does not work on the FunKey. It would then need some investigation and I guess that's disabled because it would not run well anyway. Maybe someone can try to enable it, but I won't tbh.
